### PR TITLE
Added DropDownButton.ClosePopupOnMouseDownDelay to allow the end-developer to tweak the delay (sometimes 100 ms is too fast)

### PR DESCRIPTION
**Pull request by GeertvanHorrik**

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Thanks for accepting so fast. Is it possible to create a prerelease package on nuget?

**Comment by batzen** [comment]
How about a stable release for tomorrow?
Just have to prepare the changelog and decide for a new version number.

**Comment by GeertvanHorrik** [comment]
That's even better :-)

I recommend that you start following GitFlow (then version is automatic).

**Comment by batzen** [comment]
When I finally find enough free time to get familiar with and try GitFlow in a test project. Don't want to play around in this repo too much.

**Pull request merged**
