### PR TITLE
Frontstage

### PR DESCRIPTION
**Pull request by maurosampietro**
OK, now i think you can actually see what i did.

Please notice i can't really deal with the titlebar. The titlebar should be hidden in the frontpage but it's behavior (move/resize) should be maintained. I wait some hint from you about that.

### CODE REVIEW

**Comment by batzen** [comment]
If you don't want to duplicate Frontstage.xaml for Office 2010 and Windows 8 please move it to the folder Themes/Generic/Controls.

You changed all lines in the project files which is not acceptable.

If you apply those two changes I will merge your PR and fix the code styling myself.
Thanks for contributing!

**Comment by maurosampietro** [comment]
I restored the project as found on main ribbon project. Don't know what happend.

I created different style for Office 2010 and Windows 8.
By the way the left panel shows transparent in any style different from Office 2013. 
In office 2013 i used: Background="{DynamicResource RibbonThemeColorBrush}"

Moreover the titlebar still shows on the frontstage but it should be hidden.
If you can please take a look at my fork.

**Comment by batzen** [comment]
The reverted project files are not part of this PR and not of your branch, currently.
And as far as I can see there are no changes for the Windows 8 theme so far.

Will have a look at the titlebar issue sometime this week.

**Comment by batzen** [comment]
Just had a look. 
You can ignore the titlebar issue. I know what I have to do to fix it.
One part is to set HideContextTabsOnOpen to true in the Frontstage, but that still leaves some parts of the titlebar visible.

**Comment by maurosampietro** [comment]
Hi batzen, 
i really don't have the experience to understand what is going on here i'm very new to github, i tried to do very concise edits to avoid problems but here they are. I call for your help here.

From the code side:

Today i solved the titlebar visibility problem simply by collapsing the titlebar on the ribbon in the Show() method of the frontstage. HideContextTabsOnOpen to true not needed.

Basic Windows 8 theme and Office 2010 drafts are ok, even if i did not pick the right color for the Font and some other minor things, the drafts are there ready to be modified.

To test how the frontstage look like with different themes i created a ShowFrontstage ToggleButton below UseBackstage.
That property simply binds to the Shown property and should reset it so that we can click on File again and make the fronstage appear again like it is the frist time the fronstage is shown.
By the way ToggleButton doesn't seem to react to that property being setting by code even if i set TwoWay binding.

i'll have more time to look at this from 7-8 jan.
Happy new year.

Hope to see a merge :)

**Comment by batzen** [comment]
Will have a look at this in the next few days.
I guess I will merge it by hand and then close your PR. As I also made changes to the backstage I have to merge some things manually anyway.

Are you ok with me merging it by hand, as that way the commits won't have your name on them?

I wish you a happy new year too (in a few hours).

**Comment by maurosampietro** [comment]
be cited is pleasant but not primary.

Mauro Sampietro
Inviato da iPhone

**Comment by batzen** [comment]
Will merge it today and rename Frontstage to StartScreen, as that's what it's called in Office itself.

**Comment by maurosampietro** [comment]
Glad to read that.
I found out the StartScreen doesn't show if 'Don't use DWM' is enabled:

animation

[Please note I switch between usebackstace/use frontstage in my fork just to reset the status of the Shown property of the StartScreen so it can be shown again]

**Comment by batzen** [comment]
Tracking this in #242 now.

**Pull request closed without merging**
