### PR TITLE
Added bindings for ItemsInRow

### PR DESCRIPTION
**Pull request by jeuxjeux20**
Also, I couldn't use the dll inside my app for some reason, XAML exception, "cannot locate resource 'file'".

The showcase works fine.

### CODE REVIEW

**Comment by jeuxjeux20** [comment]
Works as expected!

**Comment by jeuxjeux20** [comment]
TwoWay and UpdateSourceTrigger.Explcit are needed to prevent the dropdown menu to overwrite the binding.

**Comment by jeuxjeux20** [comment]
Had to put it on the Loaded event. There should be a better solution 🤔

**Comment by batzen** [comment]
There are already the methods OnMaxItemsInRowChanged and OnMinItemsInRowChanged which just have a condition on them. Just removing the conditions should achieve the same. I just can't remember why i put those conditions there...

But i just noticed that, in case anyone would ever want to change this while the dropdown is open, would break.

**Comment by jeuxjeux20** [comment]
Oh i didn't notice them, they weren't updating though :/

**Comment by jeuxjeux20** [comment]
Well, after actually looking a bit at this commit, the OnChanged events only takes place on the GalleryPanel and GalleryPanelContainer, but no updating on the InRibbonGallery side.

**Comment by jeuxjeux20** [comment]
Well yeah you're actually right, looking at the code once more and i find the attached event.

**Comment by jeuxjeux20** [comment]
Normally fixed the conditions to something more meaningful.

**Comment by batzen** [comment]
Fixed this without the Min/Max calls as those would make the calls dependent on each other.

**Pull request closed without merging**
