### PR TITLE
Adds customizable keys for activating the key tips

### PR DESCRIPTION
**Pull request by pschimmel**
As announced in Issue #559 I extended the ribbon service that the implementer can change the default keys that activate key tips.

This can become handy when the default keys are needed for other functions in the application.

### CODE REVIEW

**Comment by batzen** [comment]
Thanks for contributing!
Will have a look at this as soon as i got some spare time. Which might take a few days.

**Comment by batzen** [comment]
Could you add some documentation for this feature to the documentation repository? That would be nice ;-)

**Comment by pschimmel** [comment]
Yes. No problem. But it might take a couple of days.

**Comment by batzen** [comment]
Yes there is https://github.com/fluentribbon/fluentribbon.github.io which hosts the website and documentation. ;-)

**Comment by batzen** [comment]
Finally found some time to have a look at this.
I am wondering if it would be more flexible to just use a list of `KeyGesture` instead of custom parsed strings. That way people could specify keys and modifiers. And it would be type safe. ;-)

**Comment by pschimmel** [comment]
I agree it could be easier to define a list of KeyGestures in XAML as they are used in other places, too and programmers are used to them.

I thought it could be a problem that some keys that are only valid when a also a modifier was provided.

When editing the IsShowOrHideKey method of the KeyTipService I was also not sure about the limitation to SystemKeys and Shift keys. But I assume that's there because of a certain reason, so I left that part untouched.

**Comment by batzen** [comment]
You are right about the modifier keys.
If `Key == None` then we can't call `gesture.Matches` but have to check that manually.
The check for `SystemKey` could be removed, the checks for shift are way too broad.
They are there because Word behaves different when certain keys are pressed and shift is also pressed.
- Shift + F10 opens the context menu
- Shift + Alt shows key tips

So the only special case left is Shift + F10. 
We should keep that special case by checking if modifier for a given gesture is None, key is F10 and shift is pressed. That case should then not show the key tips. As that shortcut is not only for Word but a global shortcut used to open a context menu.

I noticed that `Space` shouldn't open key tips as Word doesn't too. Don't know why it's there.
So we should just remove it and add it as a breaking change to the changelog.

**Comment by pschimmel** [comment]
I just pushed the changes that use KeyGestures.
I removed the checks for SystemKey and the check for Shift keys. Instead it checks against a list of invalid gestures.

Some parts might require some optimization, but it's already a bit late :)

**Comment by batzen** [comment]
There are a few things that are problematic in the code.
Should i add comments to the lines you changed and you fix the issues, or should i accept your PR and push changes fixing the issues?
The second approach would be faster and wouldn't cause us to go back and forth. ;-)

**Comment by pschimmel** [comment]
I agree. Just go ahead and do the changes. I'll take a look at them when the PR is merged with the main branch.

**Comment by batzen** [comment]
Ok, i have admit that `KeyGesture` doesn't work as well as i thought because we can't check modifier-keys on KeyUp.
I will change the code to just use a list of `Key`.

By that we still get type-safe keys because you can use
```
<Fluent:Ribbon.KeyTipKeys>
    <Key>A</Key>
</Fluent:Ribbon.KeyTipKeys>
```

**Pull request merged**
