### PR TITLE
Office 2010 and Windows8 StartScreenTabControl style and other minor fixes

### PR DESCRIPTION
**Pull request by maurosampietro**
I created a generic StartScreenTabControl style suitable for Office2010 and Windows8 with and without dwm. The old StartScreenTabControl is now a specialized version for Office2013.

Office 2013 StatusBar height should be 23, with no border margin etc.

### CODE REVIEW

**Comment by maurosampietro** [comment]
Project files are not changed inspite git says i added and removed everything.
I think nuget/restore is responsible of this to happen.

**Comment by batzen** [comment]
First thanks for contributing and i don't want to sound rude, so please understand that it's just emotionless technical when i write something.

When you didn't change the project files, don't commit them (or at least do a manual diff and revert everything you didn't change explicitly).

As I said, i don't want duplicated style/template files for the StartScreenTabControl. Please don't introduce new ones. Beside that, the Office2013 file you introduced is even missing from this this PR.

As there is no StartScreen at all in Office 2010 and Windows 8 I'd like to have them fullscreen as in Office 2013. Otherwise (non fullscreen) they don't even make sense to me. The only styling issue which we currently have is when someone is using the StartScreen with said themes and DWM is not available. So in my opinion the solution can't be to make the StartScreen non fullscreen for those themes but to somehow fix the 1-2 pixel issue in a different way.

To achieve margins with bound values there is already ThicknessConverter.

The StatusBar changes look good to me.

**Comment by maurosampietro** [comment]
Hi batzen,
feel free to write down straight with me, i'm not getting offended.

At the moment the startscreen looks bad for styles different from office2013 so something has to be done (this is how it looks with dwm on Office2010 and Windows8):

image

In office 2010 and windows 8 if dwm is used we can't use fullscreen startscreen because it does not cover entirely the glass titlebar and it looks very bad (only the left panel covers it). For that reason my idea was to make the startscreentabcontrol not cover the titlebar at all and then hide the caption and icon of the titlebar. I didn't do the latter for tech reasons yet .

Btw I think the result is pretty cool with dwm disabled (just imagine there's no caption and icon on the title bar). Tell me If you like this or not.
image

In case dwm is used if you like i can use fullscreen Office2013 style and try to cover the titlebar completely both on the left and right panels and see how it looks.

Just tell me your thoughts.

**Comment by batzen** [comment]
Now i get what you are trying to do.
I will implement it that way so you can see what i want to do in the future to prevent template duplication.

I think the window icon and caption can stay where they are in Office 2010 and Windows 8. If we also hide them people might get confused.

**Comment by batzen** [comment]
Do you want to create a new PR for your changes in RibbonStatusBar, or should i just add those?

**Comment by maurosampietro** [comment]
There are a few other things to take care of for the status bar. I will create a new PR. 

Mauro Sampietro
Inviato da iPhone

**Comment by maurosampietro** [comment]
"I think the window icon and caption can stay where they are in Office 2010 and Windows 8. If we also hide them people might get confused."

With regard to the above please consider that the left panel will also show the caption and maybe the icon (it could completely replace the titlebar in this case), so to avoid repetition a flag like 'HideTitleBarContent' to hide the caption and icon might be desirable.

**Comment by batzen** [comment]
Will track such a flag as part of #250

**Pull request closed without merging**
