### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by wstaelens**
start for the documentation

### CODE REVIEW

**Comment by batzen** [comment]
Again, nice that you are interested in helping.

The index.md provided by caliburnmicro is used for the github page there.
Whereas the documentation folder in this project is not used for a github page.
So things like the "layout" and "title" things contained in the index.md don't get rendered as intended here on github.

I could create a github page and we could move the current content of documentation to that repository then.
This means that i will reject this PR and you will have to do it again for the then newly created repository.
Agreed?

**Comment by wstaelens** [comment]
yes, maybe you can create the structure as I did so that I can add content already

**Comment by batzen** [comment]
I hope I can find some time to get this done this weekend.

**Comment by batzen** [comment]
I created the repository, but I probably will have to invest some time getting to know jekyll, which is the engine behind the caliburn.micro pages. Will update you when I think I am ready to go.

**Comment by batzen** [comment]
Making progress with the page. Should be up and running by thursday.

**Comment by wstaelens** [comment]
ok great!

**Comment by batzen** [comment]
Finished the first version: https://github.com/fluentribbon/fluentribbon.github.io

**Comment by batzen** [comment]
Will close this PR because of the newly created repo.

**Pull request closed without merging**
