### PR TITLE
Windows8 theme

### PR DESCRIPTION
**Pull request by pekspro**
Here is my attempt to create a Windows 8 theme for this project. I’ve learned a lot from doing this :-). My respect for the original project is now larger than ever.

I think it’s very close to what is used in Windows 8 in Explorer, WordPad etc. My application that I’m using this for now looks the way I wanted from start.

I have some comments and questions:

1. When you open a gallery you will see a strange scroll bar. I haven’t tried to solve this yet. The reason for this is that you get the same scroll bar in the Office 2010. Is this by purpose?

strange_gallery_scroll_bar

Update 2015-01-25: I have actually removed the customized scrollbar and using the original instead. And it looks fine now I think.

 
2. The control templates FluentPopupMenuControlTemplate and PopupMenuControlTemplate is a copy from the Office 2010, but these doesn’t seem to be used anywhere. Could these be removed?

Update 2015-01-25: The same question for ScrollButtonControlTemplate.

3. A bunch of files is exactly the same as in the Office 2010. To simplify maintaining this I could remove these files and modify Generic.txt to take them from the Office 2010 theme. I leave it to you to decide what’s best.

4. I haven’t looked on the images at all, so I’m not really sure what to do with them. I would prefer to use to vector based images instead of bitmaps where it’s possible. Ribbon collapse/expand seems to be easy to change to a path. I will look deeper into this if it’s fine with you.

5. There is still some optimizing to do (removing things that isn’t used etc). I will do this later when these questions has been resolved. I also need to test this in Windows 7.

Update 2015-01-25: Now I’m quite close to finish I think. There is still some fine tuning to do (I have couple of TODO:s in the XAML to sort out – there are some couple of things I don’t understand how they are used). But in general things works fine. 

I hope you like this :-).

### CODE REVIEW

**Comment by batzen** [comment]
I will write an answer within next week, way too busy currently.

**Comment by pekspro** [comment]
No problem, take your time. This not in any way urgent for me. I still working on some minor tweaks.

**Comment by batzen** [comment]
To answer your questions:
1. If those templates aren't used feel free to remove them, but please do that in a separate pull request.
2. Please remove duplicated files. It just makes maintaining everything harder.
3. Please don't copy/duplicate the images. Feel free to replace the images with vector graphics, but please do that in a separate pull request.

As soon as you removed the duplicated files i will have a final look at your changes and then merge the pull request.

**Comment by pekspro** [comment]
Great! I just checked in final changes where duplicates are removed.

When it comes to the unused templates I prefer that you remove them. I’m not trying to avoid doing the work, I just assume you know what is safe to remove better than me :-). I have left a couple off TODO:s in the xaml file. I find some more things that I wasn’t sure off, or didn’t know how to test.

I’ll wait the vector images a couple of days.

**Pull request merged**
